<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/src/bootstrap.php';
use LGFC\{BallotHistory,Elections,MovieNights};
function check(bool $ok,string $label):void{if(!$ok)throw new RuntimeException($label);echo "PASS - $label\n";}
function rejects(callable $fn,string $type,string $label):void{try{$fn();}catch(Throwable $e){check($e instanceof $type,$label);return;}throw new RuntimeException($label);}
$p=new PDO('sqlite::memory:');$p->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$p->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE,PDO::FETCH_ASSOC);
$p->exec(file_get_contents(__DIR__.'/../db/schema.sql'));$p->exec(file_get_contents(__DIR__.'/../db/seed.sql'));$p->exec("UPDATE users SET role='organiser' WHERE id=1");
MovieNights::migrate($p);MovieNights::migrate($p);
check(MovieNights::current($p)===null && MovieNights::latestId($p)===0,'no fabricated announcement after migration');
rejects(fn()=>MovieNights::announce($p,2,'direct',1,'2099-01-01',0,1),DomainException::class,'member cannot announce');
rejects(fn()=>MovieNights::announce($p,1,'direct',1,'2020-01-01',0,1),InvalidArgumentException::class,'past date rejected');
rejects(fn()=>MovieNights::announce($p,1,'direct',1,'2099-02-30',0,1),InvalidArgumentException::class,'invalid date rejected');
rejects(fn()=>MovieNights::announce($p,1,'election',1,'2099-01-01',0,1),DomainException::class,'election without ballots cannot announce');
check(MovieNights::openId($p)===1 && $p->query('SELECT COUNT(*) FROM election_results')->fetchColumn()==0,'failed announcement rolls back closure and result');
$ids=Elections::candidateIds($p,1);$revision=Elections::submit($p,1,1,$ids);
$announcement=MovieNights::announce($p,1,'election',1,'2099-01-01',0,1);
$current=MovieNights::current($p);
check($current['source']==='election' && (int)$current['movie_id']===1 && MovieNights::openId($p)===0,'closing and announcing winner are atomic');
check(Elections::finalResult($p,1)['winner']===1 && !MovieNights::cancelled($p,1),'democratic closure keeps genuine frozen winner');
check($p->query('SELECT COUNT(*) FROM movie_watches')->fetchColumn()==0,'announcement never marks a film watched');
rejects(fn()=>MovieNights::announce($p,1,'direct',2,'2099-01-02',0,0),DomainException::class,'stale plan cannot replace newer announcement');
$next=Elections::open($p,'Next election');
rejects(fn()=>MovieNights::announce($p,1,'direct',2,'2099-01-02',$announcement,0),DomainException::class,'stale form cannot cancel an election opened since load');
rejects(fn()=>MovieNights::announce($p,1,'election',1,'2099-01-02',$announcement,$next),DomainException::class,'older winner cannot silently close a different election');
$nextIds=array_reverse(Elections::candidateIds($p,$next));
$nextRevision=Elections::submit($p,$next,1,$nextIds);
$before=Elections::currentResult($p,$next);
$direct=MovieNights::announce($p,1,'direct',2,'2099-01-02',$announcement,$next);
check(MovieNights::cancelled($p,$next) && MovieNights::openId($p)===0,'direct selection cancels the current election');
check(Elections::finalResult($p,$next)===$before && count(Elections::ballots($p,$next))===1,'cancelled election retains exact ballots and archived tally');
check(BallotHistory::snapshot($p,$next)['cancelled']===true,'history explicitly identifies cancellation');
check((int)MovieNights::current($p)['movie_id']===2 && MovieNights::current($p)['source']==='direct','announced film can differ from archived leader');
rejects(fn()=>Elections::submit($p,$next,1,$ids),DomainException::class,'stale ballot after cancellation creates no vote');
rejects(fn()=>MovieNights::announce($p,1,'election',$next,'2099-01-03',$direct,0),DomainException::class,'cancelled result cannot be announced as democratic winner');
$newDate=MovieNights::reschedule($p,1,'2099-01-03',$direct,0);
check(MovieNights::current($p)['source']==='direct' && MovieNights::current($p)['scheduled_on']==='2099-01-03','date-only update preserves selection source');
MovieNights::clear($p,1,$newDate,0);$cleared=MovieNights::latestId($p);
check(MovieNights::current($p)===null && MovieNights::cancelled($p,$next),'clear announcement never reopens a cancelled election');
rejects(fn()=>MovieNights::announce($p,1,'direct',3,'2099-01-04',$newDate,0),DomainException::class,'clearing retains stale-form protection');
$p->exec("UPDATE movies SET title='PRIVATE TITLE',mystery_alias='Secret choice',summary='PRIVATE SUMMARY',image_url='https://example.org/private.jpg' WHERE id=6");
MovieNights::announce($p,1,'direct',6,'2099-01-04',$cleared,0);$mystery=MovieNights::current($p);
check($mystery['movie']['title']==='Secret choice' && $mystery['movie']['release_year']===null && !str_contains(json_encode($mystery),'PRIVATE'),'announcements preserve mystery metadata filtering');
$last=MovieNights::latestId($p);
rejects(fn()=>MovieNights::announce($p,1,'direct',999,'2099-01-04',$last,0),InvalidArgumentException::class,'unknown films rejected without changing announcement');
check(MovieNights::latestId($p)===$last,'failed direct choice leaves no announcement record');
$open=Elections::open($p,'Still voting');
MovieNights::reschedule($p,1,'2099-01-05',$last,$open);
check(MovieNights::openId($p)===$open,'date-only adjustment does not cancel a different ongoing vote');
$last=MovieNights::latestId($p);
$p->exec("UPDATE users SET role='member' WHERE id=1");
rejects(fn()=>MovieNights::clear($p,1,$last,$open),DomainException::class,'organiser demotion is rechecked inside write');
check($p->query('SELECT COUNT(*) FROM ballot_revisions')->fetchColumn()==2,'all original ballot revisions retained');
